# Generated by Django 6.0.6 on 2026-06-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('can_manage_rooms', models.BooleanField(default=False, verbose_name='客房管理')),
                ('can_manage_bookings', models.BooleanField(default=False, verbose_name='预订管理')),
                ('can_check_in', models.BooleanField(default=False, verbose_name='办理入住')),
                ('can_check_out', models.BooleanField(default=False, verbose_name='办理退房')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='客户管理')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='查看报表')),
                ('can_manage_system', models.BooleanField(default=False, verbose_name='系统设置')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='员工管理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('id_card', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('is_active_staff', models.BooleanField(default=True, verbose_name='在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
