# Generated by Django 6.0.6 on 2026-06-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True, verbose_name='房间号')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
                ('status', models.CharField(choices=[('available', '空闲'), ('occupied', '住人'), ('reserved', '预定'), ('dirty', '脏房'), ('maintenance', '维修')], default='available', max_length=20, verbose_name='状态')),
                ('price_override', models.DecimalField(decimal_places=2, default=0, help_text='0表示使用房型默认价格', max_digits=10, verbose_name='价格覆盖')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间管理',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='房型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='房型代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础价格')),
                ('weekend_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='周末价格')),
                ('holiday_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='节假日价格')),
                ('capacity', models.IntegerField(default=2, verbose_name='容纳人数')),
                ('bed_type', models.CharField(default='大床', max_length=50, verbose_name='床型')),
                ('area', models.CharField(blank=True, max_length=20, verbose_name='面积')),
                ('amenities', models.TextField(blank=True, verbose_name='设施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型管理',
            },
        ),
        migrations.CreateModel(
            name='RoomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('category', models.CharField(default='消耗品', max_length=50, verbose_name='类别')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(choices=[('good', '完好'), ('damaged', '损坏'), ('missing', '缺失')], default='good', max_length=20, verbose_name='状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '房间物品',
                'verbose_name_plural': '房间物品',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='房型'),
        ),
    ]
