# Generated by Django 6.0.6 on 2026-06-26 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('room_type_name', models.CharField(blank=True, max_length=50, verbose_name='预订房型')),
                ('check_in_date', models.DateField(verbose_name='入住日期')),
                ('check_out_date', models.DateField(verbose_name='离店日期')),
                ('guest_count', models.IntegerField(default=1, verbose_name='入住人数')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('checked_in', '已入住'), ('checked_out', '已离店'), ('cancelled', '已取消'), ('no_show', '未到')], default='pending', max_length=20, verbose_name='订单状态')),
                ('channel', models.CharField(choices=[('online', '在线预订'), ('front_desk', '前台预订'), ('phone', '电话预订'), ('ota', 'OTA渠道'), ('walk_in', '散客')], default='online', max_length=20, verbose_name='渠道来源')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总额')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订金/押金')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='入住时间')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金金额')),
                ('id_card_verified', models.BooleanField(default=False, verbose_name='身份已验证')),
                ('guest_names', models.TextField(blank=True, verbose_name='同住人')),
                ('key_card_no', models.CharField(blank=True, max_length=50, verbose_name='房卡号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='关联订单')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='入住房间')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='办理人')),
            ],
            options={
                'verbose_name': '入住记录',
                'verbose_name_plural': '入住记录',
            },
        ),
        migrations.CreateModel(
            name='CheckOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(auto_now_add=True, verbose_name='退房时间')),
                ('room_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='房费')),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他消费')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='违约金')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费总额')),
                ('deposit_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='抵扣押金')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实收金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('card', '刷卡'), ('wechat', '微信支付'), ('alipay', '支付宝'), ('credit', '挂账'), ('mixed', '混合支付')], default='cash', max_length=20, verbose_name='支付方式')),
                ('invoice_no', models.CharField(blank=True, max_length=50, verbose_name='发票号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='关联订单')),
                ('check_in_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.checkinrecord', verbose_name='关联入住')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='办理人')),
            ],
            options={
                'verbose_name': '退房记录',
                'verbose_name_plural': '退房记录',
            },
        ),
    ]
