# Generated by Django 6.0.6 on 2026-06-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='等级名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='等级代码')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, help_text='0.85表示85折', max_digits=3, verbose_name='折扣率')),
                ('points_rate', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='积分倍率')),
                ('late_checkout_hours', models.IntegerField(default=0, verbose_name='延迟退房(小时)')),
                ('min_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费门槛')),
                ('description', models.TextField(blank=True, verbose_name='等级说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='M', max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('nationality', models.CharField(default='中国', max_length=50, verbose_name='国籍')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计消费')),
                ('total_stays', models.IntegerField(default=0, verbose_name='入住次数')),
                ('preferences', models.TextField(blank=True, verbose_name='偏好备注')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='黑名单')),
                ('blacklist_reason', models.TextField(blank=True, verbose_name='拉黑原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.membershiplevel', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
